services:
  - type: web
    name: telegram-bot-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=1 --threads=2 --timeout=120 --bind 0.0.0.0:$PORT
    autoDeploy: true
